image: python:3.11

setup_script:
  - apt-get update
  - apt-get install -y curl git
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  - node -v
  - pip install --upgrade pip
  - pip install networkx pyyaml codecarbon

cache:
  key: greenpipeline-cache
  paths:
    - .cache/pip
    - /root/.cache/pip

network_policy:
  include_recommended_allowed: true
