"""Generate Gitlab MR comments based on pipeline analysis."""

from __future__ import annotations

from greenpipeline import PipelineResult


def generate_gitlab_comment(result: PipelineResult) -> str:
    """Generate a professional markdown comment for GitLab MRs."""
    report = result.optimization
    carbon = result.carbon
    reasoning = result.reasoning
    simulation_status = result.simulation_status

    score = reasoning.efficiency_score if reasoning else 0

    if reasoning and reasoning.explanations:
        suggestions = "\n".join(f"- {s}" for s in reasoning.explanations)
    elif report and report.suggestions:
        suggestions = "\n".join(f"- {s.description}" for s in report.suggestions)
    else:
        suggestions = "No major optimizations detected. Your pipeline is efficient! ✅"

    return f"""### 🌿 GreenPipeline AI Report

**Execution Mode**: {simulation_status}

**Pipeline Efficiency Score**: {score}/100

**Pipeline Runtime**  
{report.original_runtime_min:.1f} min → **{report.optimized_runtime_min:.1f} min**

**Carbon Footprint**  
{carbon.current_emissions_kg:.4f} kg → **{carbon.optimized_emissions_kg:.4f} kg CO₂**

---

### ⚡ Optimization Suggestions

{suggestions}"""


def generate_gitlab_comment_with_patch(result: PipelineResult) -> str:
    """Generate the MR comment and append the optimized YAML patch inline."""
    comment = generate_gitlab_comment(result)

    if not result.optimized_yaml:
        return comment

    return f"""{comment}

---

### 🛠 Suggested Pipeline Patch

```yaml
{result.optimized_yaml}
```

---

Generated by **GreenPipeline AI**
"""
